name: Terraform apply

on: 
  workflow_dispatch:


jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Configuration
        run: terraform validate

      - name: Plan Changes
        run: terraform plan -out=tfplan

      - name: Apply Changes
        run: terraform apply tfplan


